# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Lindsey
tagline:          'Professional Resume and Portfolio'
description:      'Higher education professional with a Bachelor''s Degree in Management from UW-Stout and a passion for marketing and technology.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:          [jekyll-paginate]